title: Dr. Nikoli A Attai
logo: /assets/img/logo.png
description: PhD Women and Gender Studies|MPhil Cultural Studies|BA Media and Communication Studies.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
